export const ADD_GROUP = 'ADD_GROUP';
export const EDIT_GROUP = 'EDIT_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const GET_GROUPS = 'GET_GROUPS';
export const SET_SELECTED_PAGE_INDEX = 'SET_SELECTED_PAGE_INDEX';
export const SET_PAGE_ELEMENT_COUNT = 'SET_PAGE_ELEMENT_COUNT';
export const SET_NAME_FOR_FILTER = 'SET_NAME_FOR_FILTER';

