export const ADD_QUESTION = 'ADD_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const SET_SELECTED_PAGE_INDEX = 'SET_SELECTED_PAGE_INDEX';
export const SET_PAGE_ELEMENT_COUNT = 'SET_PAGE_ELEMENT_COUNT';
export const SET_TEXT_FOR_FILTER = 'SET_TEXT_FOR_FILTER';
export const SET_TOPIC_FOR_FILTER = 'SET_TOPIC_FOR_FILTER';

