export const ADD_TOPIC = 'ADD_TOPIC';
export const EDIT_TOPIC = 'EDIT_TOPIC';
export const DELETE_TOPIC = 'DELETE_TOPIC';
export const GET_TOPICS = 'GET_TOPICS';
export const SET_SELECTED_PAGE_INDEX = 'SET_SELECTED_PAGE_INDEX';
export const SET_PAGE_ELEMENT_COUNT = 'SET_PAGE_ELEMENT_COUNT';
export const SET_TITLE_FOR_FILTER = 'SET_TITLE_FOR_FILTER';

