version: '3.3'
services:
  back_end:
    build: ./back-end/
    ports:
      - "8090:8090"
    depends_on:
      - postgres-db
    environment:
      POSTGRES_USER: arayik
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: quiz_app  # Optional if your application reads the database name as well

  postgres-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: quiz_app
      POSTGRES_USER: arayik
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-data:/var/lib/postgresql/data

  react_app:
    build: ./client/univercity-client/
    ports:
      - "3000:3000"

volumes:
  postgres-data:

