version: '3.3'

services:
  back_end:
    image: maven:3.8.4-openjdk-11
    working_dir: /app
    volumes:
      - ./back-end:/app
    ports:
      - "8090:8090"
    depends_on:
      - postgres-db
    environment:
      POSTGRES_USER: arayik
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: quiz_app
    command: >
      /bin/sh -c "mvn clean compile package && java -jar target/univercity_ecosystem-1.0.jar"

  postgres-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: quiz_app
      POSTGRES_USER: arayik
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-data:/var/lib/postgresql/data

  react_app:
    image: node:14
    working_dir: /app
    volumes:
      - ./client/univercity-client:/app
    ports:
      - "3000:3000"
    command: /bin/sh -c "npm install && npm install -g serve && npm run build && serve -s build"

volumes:
  postgres-data:

